parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     rk000277_lecroix
    database_user:     rk000277_lecroix
    database_password: ROtu50kadu
    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~
    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
