<?php

namespace SanJorge\SanJorgeBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ClientesController__JMSInjector
{
    public static function inject($container) {
        $instance = new \SanJorge\SanJorgeBundle\Controller\ClientesController();
        return $instance;
    }
}
