parameters:
#    san_jorge.example.class: SanJorge\SanJorgeBundle\Example

services:
#    san_jorge.example:
#        class: %san_jorge.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
